python_requirements(
    source="pants-requirements.txt",
    module_mapping={
        "faust-streaming": ("faust",),
        "mode-streaming": ("mode",),
        "launchdarkly-server-sdk": ("ldclient",),
        "google-api-python-client": ("googleapiclient",),
        "kafka-python": ("kafka",),
        "django-postgres-extra": ("psqlextra",),
        "python-decouple": ("decouple",),
        "social-auth-app-django": ("social_django",),
        "django-js-reverse": ("django_js_reverse",),
        "rest_slack": ("django-rest-slack",),
        "drf-yasg": ("drf_yasg",),
        "django-cors-headers": ("corsheaders",),
        "django-axes": ("axes",),
        "graphene-django": ("graphene_django",),
        "djangorestframework-simplejwt": ("rest_framework_simplejwt",),
        "django-model-utils": ("model_utils",),
        "google-cloud-monitoring": ("google.cloud.monitoring",),
        "gremlinpython": ("gremlin_python",),
        "python-registry": ("Registry",),
        "pyre2": ("re2",),
        "aliyun-python-sdk-core": ("aliyunsdkcore",),
        "aliyun-python-sdk-ecs": ("aliyunsdkecs",),
        "aliyun-python-sdk-sts": ("aliyunsdksts",),
        "aliyun-python-sdk-ram": ("aliyunsdkram",),
        "aliyun-python-sdk-rds": ("aliyunsdkrds",),
        "aliyun-python-sdk-kms": ("aliyunsdkkms",),
        "pysaml2": ("saml2",),
        "slackclient": ("slack",),
        "python-magic": ("magic",),
        "pycryptodome": ("Crypto",),
        "pyelftools": ("elftools",),
        "yara-python": ("yara",),
        "python-evtx": ("Evtx",),
    },
)

