[GLOBAL]
pants_version = "2.22.0rc2"
backend_packages = [
  "pants.backend.python",
]
pantsd_max_memory_usage = "8GiB"

[python]
interpreter_constraints = [">=3.8,<3.9"]
enable_resolves = true
resolves = { python-default = "python-default.lock" }
default_resolve = "python-default"

[python-infer]
init_files = "always"

[source]
marker_filenames = ["SOURCE_ROOT"]

[python-repos]
indexes = [
    "https://pypi.org/simple/",
  ]

[pytest]
execution_slot_var = "PANTS_EXECUTION_SLOT"

[subprocess-environment]
env_vars.add = [
    "LA_LIBRARY_FILEPATH",
]

[test]
report = true

extra_env_vars = [
    "TMPDIR",
    "LANG",
    "LC_CTYPE",
    "LC_ALL",
    "SRC_ROOT",
]

[cli.alias]
deps = "dependencies --dependencies-closed"
tdeps = "dependencies --dependencies-transitive --dependencies-closed"
depe = "dependees --dependees-closed"
tdepe = "dependees --dependees-transitive --dependees-closed"
ft = "filter --target-type=python_tests"

[stats]
log = false
