
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-asyncio",
        "//:reqs#pytest-django",
    ]
)
