
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#attrs",
        "//:reqs#backoff",
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#httpx",
        "//:reqs#launchdarkly-server-sdk",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
        "//:reqs#sentry-sdk",
        "//:reqs#typeguard",
    ]
)
