
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#marshmallow",
        "//:reqs#marshmallow-enum",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
        "//:reqs#typing-inspect",
    ]
)
