
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#boto3",
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#moto",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
        "//:reqs#python-dateutil",
        "//:reqs#pytz",
    ]
)
