
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#cachetools",
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#fastavro",
        "//:reqs#faust-streaming",
        "//:reqs#launchdarkly-server-sdk",
        "//:reqs#prometheus-client",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
        "//:reqs#typeguard",
    ]
)
