
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#more-itertools",
        "//:reqs#psycopg2-binary",
        "//:reqs#pydantic",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
    ]
)
