
python_tests(
    name="tests",
    dependencies=[
        "//:reqs#coverage",
        "//:reqs#django",
        "//:reqs#django-stubs",
        "//:reqs#haikunator",
        "//:reqs#launchdarkly-server-sdk",
        "//:reqs#psycopg2-binary",
        "//:reqs#pytest",
        "//:reqs#pytest-django",
        "//:reqs#python-dateutil",
        "//:reqs#pyyaml",
        "//:reqs#typeguard",
        "//:reqs#typing-extensions",
    ]
)
